version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo-s
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

  mongo-express:
    image: mongo-express
    container_name: mongo-express-s
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo

  cpsserver:
    image: cpsserver
    container_name: cpsserver-s
    build: .
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - DB_NAME=cpsbase
    ports:
      - 30001:30001
    depends_on:
      - mongo

networks:
  default:
    name: servicenet
